### ISSUE TITLE
General redirects from old urls to new ones

### ISSUE THREAD

**Issue by gcharang** [Shigma/vuepress-plugin-redirect#1]
## Feature request

A way to redirect an older url to an existing url in the current site structure. 
Example:
Old link: `https://docs.examplesite.com/intro/basics.html` to be redirected to 
New Link: `https://docs.examplesite.com/start-here/introduction.html` 

The absence of a straightforward way to do this has been discussed in [Issue #160](https://github.com/vuejs/vuepress/issues/160) of the Vuepress repo.   

#### What problem does this feature solve?

When reorganizing the directory structure as well as changing the names of files and directories, this feature is useful to not break the existing bookmarks and links from other websites.

This plugin [vuepress-plugin-redirect](https://vuepress.github.io/en/plugins/redirect/) currently works for a subset of redirects where "redirecting any page to its subpages" is needed. 

#### What does the proposed API look like?

I suggest requiring a file like https://github.com/vuejs/vue-router/blob/dev/docs/.vuepress/public/_redirects which contains the old and new links side by side or as an array of JSONs. The plugin should read the file to generate the redirects.

#### How should this be implemented in your opinion?

I am not sure, but the redirects in the above-linked file are working in the `vue-router`'s website: `https://router.vuejs.org/`
Ex: https://router.vuejs.org/en/essentials/getting-started.html
properly gets redirected to
https://router.vuejs.org/guide/

#### Are you willing to work on this yourself?

I am a newbie to JS and Vue, happily using Vuepress to create documentation like: https://developers.komodoplatform.com/

But, @Shigma [suggested](https://github.com/vuejs/vuepress/issues/160#issuecomment-479844330) they were considering to support this feature in the plugin [vuepress-plugin-redirect](https://vuepress.github.io/en/plugins/redirect/)

**Comment by shigma** [comment]
Published `1.2.0-alpha.0`. Can you help check whether it satisfies your needs?

docs: https://github.com/vuepress/vuepress-plugin-redirect/tree/next#alias

**Comment by gcharang** [comment]
Thank you very much! It works exactly as I needed.
