### ISSUE TITLE
Redirect with 301 HTTP status code

### ISSUE THREAD

**Issue by samajammin** [Shigma/vuepress-plugin-redirect#3]
Thanks for building this plugin!

I noticed testing the example on this page:
https://vuepress.github.io/en/plugins/redirect/

It appears the HTTP response is a 404:
![Image 2019-09-17 at 3 25 20 PM](https://user-images.githubusercontent.com/8097623/65084330-c44cd180-d95f-11e9-8244-25765bef69a2.png)

Is it possible to return a 301 instead? That's a best practice for SEO purposes.

**Comment by meteorlxy** [comment]
This plugin handle redirection in client side, i.e. in `404.html` file.

I'm afraid that HTTP status codes are out-of-scope of this plugin, and even out-of-scope of vuepress
